using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class BossBullet2 : MonoBehaviour
{
    public int damage = 1;  // ’e‚Ìƒ_ƒ[ƒW


    void Start()
    {
        // ’e‚ğ”­Ë‚·‚éSE‚ğÄ¶
    }

    void OnTriggerEnter2D(Collider2D collision)
    {
        if (collision.gameObject.CompareTag("SkyBoss"))
        {
            SkyBoss2HP bossHp = collision.gameObject.GetComponent<SkyBoss2HP>();

            if (bossHp != null)
            {
                bossHp.Damage(damage);
            }
            Destroy(gameObject);    // ’e‚ğÁ‚·
        }
    }

    // ’e‚ª‰æ–ÊŠO‚Éo‚½‚çíœ
    void OnBecameInvisible()
    {
        Destroy(gameObject);
    }
}
